### ISSUE TITLE
Pseudocode

### ISSUE THREAD

**Issue by ketch** [ketch/positiveRK#22]
Although it is much better now, there are still major problems with the pseudocode.  For instance:

- "result correct" is not defined
- The algorithm will never terminate because the time is never updated
- The algorithm will also not terminate because if the LP is infeasible, then it will again be infeasible every time the loop is executed

There are additional problems; please go over this carefully and make sure it is correct.

**Comment by snuesslein** [comment]
> - "result correct" is not defined

I have removed it because the only goal was to test whether the result returned by the solver is reasonable. This does not fit into the new position of the pseudocode in the paper and is not needed to describe the algorithm.
@ketch There was a 
> TODO: define these

Does the term 'feasible' need an definition? Or should we rather use `$\tilde b$ found`?
> - The algorithm will never terminate because the time is never updated 

There already was an update step `$t \leftarrow t + \dt$, $n \leftarrow n+1$` Is there a problem with this statement? I made more clear that it is called by using GOTO statements

>- The algorithm will also not terminate because if the LP is infeasible, then it will again be infeasible every time the loop is executed

The idea was to do the reduction inside the stepsize control (This is also the way it i done in the python implementation). There has been an explanation in the paper but i think we removed it for some reason. 
Now I have put it directly in the pseudocode to make it clear. 
I have also added a test for the total error.

Hopefully the changed version is easier to understand.

**Comment by ranocha** [comment]
I think "feasible" does not need a definition here. Otherwise, the pseudocode looks okay for me. (I've made a minor change in #26.)

**Comment by ketch** [comment]
Feasible is fine.

There was no time update; @ranocha added it after I pointed it out.  It's probably better not to add GOTO statements unless they are necessary.

**Comment by ranocha** [comment]
I'm not sure about the GOTO statements. For me, they are fine and not worse than keeping track of the `success` variable that was used before.

**Comment by snuesslein** [comment]
Ok fine

Unfortunately i did not check the pseudocode from the time the issue was written and did not recognize that @ranocha already fixed the update error. I'm sorry for that.

I first tried to write the code without GOTO statements, because i am also not very keen on them. 
But i think the code is far more readable with the GOTO statements.
I would go with @ranocha to keep the GOTO statement instead of some state variable.

**Comment by ketch** [comment]
>I would go with @ranocha to keep the GOTO statement instead of some state variable.

Okay, I'm fine with that.

**Comment by ranocha** [comment]
Can we close this issue?
